name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  cargo-test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
      # Don't check the generated file, it doesn't quite match the style of rustfmt yet.
      # - run: cargo fmt --check
      - run: cargo fmt -p generate-api --check
      - run: cargo clippy
      - run: cargo clippy -p generate-api

  rust_versions:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust_version: ["beta", "nightly", "1.56"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
